apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nestjs.secret.name }}
type: Opaque
data:
  DB_HOST: {{ .Values.nestjs.secret.data.DB_HOST | b64enc | quote }}
  DB_PORT: {{ .Values.nestjs.secret.data.DB_PORT | b64enc | quote }}
  DB_USERNAME: {{ .Values.nestjs.secret.data.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD: {{ .Values.nestjs.secret.data.DB_PASSWORD | b64enc | quote }}
  DB_NAME: {{ .Values.nestjs.secret.data.DB_NAME | b64enc | quote }}
  DB_SYNCHRONIZE: {{ .Values.nestjs.secret.data.DB_SYNCHRONIZE | b64enc | quote }}
