apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.secret.data.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.data.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.secret.data.POSTGRES_DB | b64enc | quote }}
  PGDATA: {{ .Values.postgres.secret.data.PGDATA | b64enc | quote }}