apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: {{ .Values.postgres.deployment.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.target_port }}